# Training settings
# Import models

training:
  multi_modal: False
  weights: False
  epochs: 20
  learning_rate: 0.0001
  batch_size: 32
  optimizer: torch.optim.Adam
  scheduler: torch.optim.lr_scheduler.CosineAnnealingLR
  loss: torch.nn.BCEWithLogitsLoss()
  bands: RGB
  number_of_classes: 11
  number_of_input_channels_s1: 2
  number_of_input_channels_s2: 3
  seed: 42
  transforms: Transforms().transform
  normalization_value: 10_000
  label_threshold: 0.05
  scheduler_max_number_iterations: 20
  scheduler_min_lr: 0
  save_model: False
  shuffle_training_data: True
  shuffle_validation_data: True
  dataset_size_small: True

environment:
  value: local