wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1681217782.778291
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.8.10
      5: 0.13.9
      8:
      - 5
data:
  desc: null
  value:
    bands: Bands.ALL
    data_set_size_small: false
    label_threshold: 0.05
    normalization_value: 10000
    shuffle_training_data: true
    shuffle_validation_data: true
    transforms: 'Compose(

      )'
model:
  desc: null
  value:
    model: master_thesis_benge_supervised_learning.supervised_baseline.model.resnet.ResNet
    multi_modal: false
    number_of_classes: 11
    number_of_input_channels_s2: 12
    weights: false
other:
  desc: null
  value:
    config_name: sentinel_2
    environment: remote
    save_model: false
training:
  desc: null
  value:
    batch_size: 32
    epochs: 20
    learning_rate: 0.001
    loss: BCEWithLogitsLoss()
    optimizer: torch.optim.adam.Adam
    scheduler: torch.optim.lr_scheduler.CosineAnnealingLR
    scheduler_max_number_iterations: 20
    scheduler_min_lr: 0
    seed: 42
