wandb_version: 1

task:
  desc: null
  value:
    task: Task.Classification
model:
  desc: null
  value:
    model: _master_thesis_benge_supervised_learning.supervised_baseline.model.resnet.ResNet
    weights: false
    number_of_classes: 11
training:
  desc: null
  value:
    modalities:
      modalities_label: multiclass_one_hot_label
      modalities:
      - sentinel_2
    epochs: 20
    learning_rate: 0.001
    batch_size: 32
    optimizer: torch.optim.adam.Adam
    scheduler: torch.optim.lr_scheduler.CosineAnnealingLR
    loss: BCEWithLogitsLoss()
    seed: 42
    scheduler_max_number_iterations: 20
    scheduler_min_lr: 0
data:
  desc: null
  value:
    normalization_value: 10000
    label_threshold: 0.05
    bands: RGB
    transforms: 'Compose(

      )'
label:
  desc: null
  value:
    transforms_label: 'Compose(

      )'
metrics:
  desc: null
  value:
    metrics: _master_thesis_benge_supervised_learning.supervised_baseline.training.classification.classification_utils.ClassificationUtils
other:
  desc: null
  value:
    save_model: false
    environment: local
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682091376.975895
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.8.16
      5: 0.14.2
      8:
      - 5
