wandb_version: 1

BANDS:
  desc: null
  value: Bands.RGB
BATCH_SIZE:
  desc: null
  value: 32
EPOCHS:
  desc: null
  value: 20
LEARNING_RATE:
  desc: null
  value: 0.001
LOSS:
  desc: null
  value: BCEWithLogitsLoss()
MODEL:
  desc: null
  value: classification_baseline.model.resnet.ResNet
MULTI_MODAL:
  desc: null
  value: false
NORMALIZATION_VALUE:
  desc: null
  value: 10000
NUMBER_OF_CLASSES:
  desc: null
  value: 11
NUMBER_OF_INPUT_CHANNELS_S1:
  desc: null
  value: 2
NUMBER_OF_INPUT_CHANNELS_S2:
  desc: null
  value: 3
OPTIMIZER:
  desc: null
  value: torch.optim.adam.Adam
SCHEDULER:
  desc: null
  value: torch.optim.lr_scheduler.CosineAnnealingLR
SEED:
  desc: null
  value: 42
TRANSFORMS:
  desc: null
  value: 'Compose(

    )'
_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1680464227.04162
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.8.10
      5: 0.13.9
      8:
      - 5
