wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1678706407.670549
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.8.10
      5: 0.13.9
      8:
      - 5
bands:
  desc: null
  value: RGB
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.001
loss:
  desc: null
  value: BCEWithLogitsLoss()
model_description:
  desc: null
  value: tmax = 4000
number_of_classes:
  desc: null
  value: 11
number_of_input_channels:
  desc: null
  value: 3
optimizer:
  desc: null
  value: torch.optim.adam.Adam
scheduler:
  desc: null
  value: torch.optim.lr_scheduler.CosineAnnealingLR
t_max:
  desc: null
  value: 4000
