wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.2
    start_time: 1679320987.388044
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.8.2
      5: 0.13.10
      8:
      - 5
bands:
  desc: null
  value: RGB
batch_size:
  desc: null
  value: 1
epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.001
loss:
  desc: null
  value: BCEWithLogitsLoss()
model_description:
  desc: null
  value: r
number_of_classes:
  desc: null
  value: 11
number_of_input_channels:
  desc: null
  value: 3
optimizer:
  desc: null
  value: torch.optim.adam.Adam
scheduler:
  desc: null
  value: torch.optim.lr_scheduler.CosineAnnealingLR
seed:
  desc: null
  value: 42
